store:
  image: busybox
  volumes:
    - '/srv/bowerpkg/store:/store'

server:
  build: .
  volumes_from:
    - store
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
  ports:
    - '127.0.0.1:31923:3000'
